const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    FETCH_PRODUCT_PAGE: 'FETCH_PRODUCT_PAGE',
    REMOVE_PRODUCT_PAGE: 'REMOVE_PRODUCT_PAGE'
}

export default ShopActionTypes;